# Generated by Django 4.1 on 2022-09-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('counselor_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('content', models.TextField()),
                ('reg_date', models.TimeField()),
            ],
            options={
                'db_table': 'counselor_review',
            },
        ),
    ]
