# Generated by Django 4.1 on 2022-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=20)),
                ('avilable_time', models.CharField(max_length=10)),
                ('certificate', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('carreer', models.TextField()),
                ('explanation', models.TextField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
