# Generated by Django 4.1 on 2022-09-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counselor',
            table='counselor',
        ),
    ]
