version: "3"

services:
    nginx:
        image: nginx:latest
        ports: 
            - "80:80"
            - "443:443"
        restart: unless-stopped
        volumes: 
            - "/jenkins/workspace/Production/nginx.conf:/etc/nginx/nginx.conf"
            - "/jenkins/workspace/Production/data/certbot/conf:/etc/letsencrypt"
            - "/jenkins/workspace/Production/data/certbot/www:/var/www/certbot"
        command : "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    back:
        depends_on:
            - nginx
        image: hugging_back/prod:latest
        ports:
            - "8080:8080"
        restart: always
    front:
        depends_on:
            - nginx
        image: hugging_front/prod:latest
        restart: always
    recom:
        depends_on:
            - nginx
        image: hugging_recom/prod:latest
        ports:
            - "8000:8000"
        restart: always
    agora:
        depends_on:
            - nginx
        image: agora-token-service:latest
        ports:
            - "8090:8080"
        restart: always
    unity:
        depends_on:
            - nginx
        image: hugging_unity/prod:latest
        ports:
            - "81:81"
        restart: always
        
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - "/jenkins/workspace/Production/data/certbot/conf:/etc/letsencrypt"
            - "/jenkins/workspace/Production/data/certbot/www:/var/www/certbot"
        depends_on:
            - nginx
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
